name: Trivy Security Scan

on:
  push:
    branches:
      - trivy

env:
  IMAGE_NAME: examen-devops
  IMAGE_TAG: latest
  DOCKER_REGISTRY: saidinamouhamed

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          trivy --version

      - name: Scan image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL \
            --output trivy-report.txt \
            $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          cat trivy-report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt