name: Trivy Security Scan

on:
  push:
    branches:
      - trivy

env:
  IMAGE_NAME: examen-devops
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ditinamouhamed

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Installer Trivy
        run: |
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz | tar xz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Scanner l'image avec Trivy
        run: |
          trivy image --severity HIGH,CRITICAL \
            --output trivy-report.txt \
            $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          cat trivy-report.txt

      - name: Sauvegarder le rapport Trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt